# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.core.validators
import django.db.models.deletion
import refund.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('UNUSABLE', 'Yaroqsiz'), ('DISLIKED', 'Yoqmagan'), ('OTHER', 'Boshqa')], max_length=200, validators=[refund.models.validate_reason_type])),
                ('custom_reason', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(5, "Sabab kamida 5 ta belgidan iborat bo'lishi kerak")])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Kamida 1 dona mahsulotni qaytarish kerak')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='loan.documentproduct')),
                ('product_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='order.productorder')),
            ],
        ),
    ]
