# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddIndex(
            model_name='debtuser',
            index=models.Index(fields=['store'], name='loan_debtus_store_i_d6d387_idx'),
        ),
        migrations.AddIndex(
            model_name='debtuser',
            index=models.Index(fields=['phone_number'], name='loan_debtus_phone_n_02acc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('store', 'phone_number'), name='uniq_active_debtuser_phone_per_store'),
        ),
    ]
