# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('seller', 'Seller'), ('deliverer', 'Yetkazuvchi'), ('cashier', 'Kassir'), ('stockman', 'Omborchi'), ('viewer', 'Faqat ko‘rish huquqi')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='store.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_roles', to='platform_user.platformuser')),
            ],
            options={
                'verbose_name': 'Do‘kon xodimi',
                'verbose_name_plural': 'Do‘kon xodimlari',
                'unique_together': {('store', 'user')},
            },
        ),
    ]
