# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
import expense.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        ('platform_user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FOOD', 'Ovqatlanish'), ('RENT', 'Ijaralar'), ('TAX', 'Soliq / kommunal'), ('DELIVERY', 'Yetkazib berish'), ('TRANSPORT', 'Transport (yo‘l, benzin, avtobus)'), ('SALARY', 'Ish haqi'), ('BONUS', 'Bonuslar / mukofotlar'), ('INTERNET', 'Internet / telefon to‘lovi'), ('MARKETING', 'Reklama / marketing'), ('EQUIPMENT', "Jihozlar xaridi / ta'miri"), ('SUPPLY', 'Kancelyariya / boshqa ofis tovarlari'), ('CLEANING', 'Tozalik va gigiyena'), ('MAINTENANCE', "Texnik xizmat (suv, elektr, ta'mir)"), ('SOFTWARE', "Dasturiy ta'minot (platforma, lisenziya)"), ('SECURITY', 'Xavfsizlik (kamera, signalizatsiya)'), ('LOAN', 'Kredit / qarz to‘lovi'), ('TAX_PENALTY', 'Jarimalar / kechiktirilgan soliqlar'), ('INSURANCE', 'Sug‘urta'), ('TRAINING', 'Trening / kurslar'), ('GIFTS', 'Mijozlarga sovg‘alar / aktsiyalar'), ('OTHER', 'Boshqa')], default='OTHER', max_length=20)),
                ('custom_reason', models.CharField(blank=True, max_length=255, validators=[expense.models.validate_custom_reason])),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=10, default=Decimal('1.0'), editable=False, max_digits=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cash_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expense', to='cashbox.cashtransaction')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='store.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='platform_user.platformuser')),
            ],
            options={
                'verbose_name': "Do'kon xarajati",
                'verbose_name_plural': "Do'kon xarajatlari",
                'ordering': ['-date'],
            },
        ),
    ]
