# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='platform_user.platformuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platforma foydalanuvchisi',
                'verbose_name_plural': 'Platforma foydalanuvchilari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateUsd',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usd_rate', serialize=False, to='platform_user.platformuser')),
                ('rate', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'USD Kursi',
                'verbose_name_plural': 'USD Kurslari',
            },
        ),
    ]
