# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox', to='store.store')),
            ],
            options={
                'verbose_name': "Do'kon kassasi",
                'verbose_name_plural': "Do'kon kassalari",
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('is_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('manual_source', models.CharField(blank=True, help_text='Qo‘lda kiritilgan manba nomi', max_length=100)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashbox.cashbox')),
            ],
            options={
                'verbose_name': 'Kassa qismi',
                'verbose_name_plural': 'Kassa qismlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
