# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0002_initial'),
        ('expense', '0001_initial'),
        ('order', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='entry_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.productentrysystem'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='expense.expense'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
