# Generated by Django 5.2.5 on 2025-08-28 09:48

import django.core.validators
import django.db.models.deletion
import order.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_user', '0001_initial'),
        ('store', '0001_initial'),
        ('store_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqami 998901234567 formatida bo'lishi kerak", regex='^\\+?[0-9]{9,15}$')])),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'), "Ayirboshlash kursi 0 dan katta bo'lishi kerak"), order.models.validate_finite])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[order.models.validate_finite])),
                ('total_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'), "To'lov miqdori 0 dan katta bo'lishi kerak"), order.models.validate_finite])),
                ('change_given', models.BooleanField(default=False)),
                ('currency_change', models.CharField(default='USD', max_length=10)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), "Qaytim miqdori manfiy bo'lishi mumkin emas"), order.models.validate_finite])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store_user.storeuser')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='platform_user.platformuser')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.store')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Kamida 1 dona mahsulot buyurtma qilinishi kerak')])),
                ('price', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'), "Narx 0 dan katta bo'lishi kerak"), order.models.validate_finite])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'), "Ayirboshlash kursi 0 dan katta bo'lishi kerak"), order.models.validate_finite])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'verbose_name': 'Buyurtmadagi Mahsulot',
                'verbose_name_plural': 'Buyurtmadagi Mahsulotlar',
            },
        ),
    ]
